# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uClientEditNew.ui'
#
# Created: Sat Jan  2 00:54:49 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_uClientEditNew(object):
    def setupUi(self, uClientEditNew):
        uClientEditNew.setObjectName("uClientEditNew")
        uClientEditNew.resize(541, 283)
        font = QtGui.QFont()
        font.setFamily("Adobe Helvetica")
        font.setPointSize(12)
        uClientEditNew.setFont(font)
        uClientEditNew.setFocusPolicy(QtCore.Qt.TabFocus)
        self.vboxlayout = QtGui.QVBoxLayout(uClientEditNew)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.clients = QtGui.QComboBox(uClientEditNew)
        self.clients.setEditable(True)
        self.clients.setObjectName("clients")
        self.gridlayout.addWidget(self.clients, 0, 1, 1, 1)
        self.TextLabel2 = QtGui.QLabel(uClientEditNew)
        self.TextLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel2.setWordWrap(False)
        self.TextLabel2.setObjectName("TextLabel2")
        self.gridlayout.addWidget(self.TextLabel2, 2, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.accPlan = QtGui.QComboBox(uClientEditNew)
        self.accPlan.setEnabled(True)
        self.accPlan.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.accPlan.setDuplicatesEnabled(False)
        self.accPlan.setObjectName("accPlan")
        self.hboxlayout.addWidget(self.accPlan)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.textLabel1_2 = QtGui.QLabel(uClientEditNew)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.hboxlayout.addWidget(self.textLabel1_2)
        self.vatFile = QtGui.QComboBox(uClientEditNew)
        self.vatFile.setObjectName("vatFile")
        self.hboxlayout.addWidget(self.vatFile)
        self.gridlayout.addLayout(self.hboxlayout, 4, 1, 1, 1)
        self.TextLabel14 = QtGui.QLabel(uClientEditNew)
        self.TextLabel14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel14.setWordWrap(False)
        self.TextLabel14.setObjectName("TextLabel14")
        self.gridlayout.addWidget(self.TextLabel14, 4, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.periodes = QtGui.QComboBox(uClientEditNew)
        self.periodes.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.periodes.setDuplicatesEnabled(False)
        self.periodes.setObjectName("periodes")
        self.hboxlayout1.addWidget(self.periodes)
        spacerItem1 = QtGui.QSpacerItem(290, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.gridlayout.addLayout(self.hboxlayout1, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem2, 6, 1, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.vat = QtGui.QCheckBox(uClientEditNew)
        self.vat.setEnabled(True)
        self.vat.setFocusPolicy(QtCore.Qt.TabFocus)
        self.vat.setTristate(False)
        self.vat.setObjectName("vat")
        self.hboxlayout2.addWidget(self.vat)
        self.budget = QtGui.QCheckBox(uClientEditNew)
        self.budget.setObjectName("budget")
        self.hboxlayout2.addWidget(self.budget)
        spacerItem3 = QtGui.QSpacerItem(57, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem3)
        self.textLabel1 = QtGui.QLabel(uClientEditNew)
        self.textLabel1.setEnabled(False)
        self.textLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.hboxlayout2.addWidget(self.textLabel1)
        self.dimension = QtGui.QComboBox(uClientEditNew)
        self.dimension.setEnabled(False)
        self.dimension.setMaxCount(12)
        self.dimension.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.dimension.setDuplicatesEnabled(False)
        self.dimension.setObjectName("dimension")
        self.hboxlayout2.addWidget(self.dimension)
        self.gridlayout.addLayout(self.hboxlayout2, 5, 1, 1, 1)
        self.TextLabel5 = QtGui.QLabel(uClientEditNew)
        self.TextLabel5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel5.setWordWrap(False)
        self.TextLabel5.setObjectName("TextLabel5")
        self.gridlayout.addWidget(self.TextLabel5, 1, 0, 1, 1)
        self.TextLabel1 = QtGui.QLabel(uClientEditNew)
        self.TextLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel1.setWordWrap(False)
        self.TextLabel1.setObjectName("TextLabel1")
        self.gridlayout.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        spacerItem4 = QtGui.QSpacerItem(171, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem4)
        self.pbSave = QtGui.QPushButton(uClientEditNew)
        self.pbSave.setObjectName("pbSave")
        self.hboxlayout3.addWidget(self.pbSave)
        self.pbCancel = QtGui.QPushButton(uClientEditNew)
        self.pbCancel.setObjectName("pbCancel")
        self.hboxlayout3.addWidget(self.pbCancel)
        self.gridlayout.addLayout(self.hboxlayout3, 7, 1, 1, 1)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.regNum = QtGui.QLineEdit(uClientEditNew)
        self.regNum.setObjectName("regNum")
        self.hboxlayout4.addWidget(self.regNum)
        spacerItem5 = QtGui.QSpacerItem(211, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem5)
        self.gridlayout.addLayout(self.hboxlayout4, 1, 1, 1, 1)
        self.textLabel3_2 = QtGui.QLabel(uClientEditNew)
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName("textLabel3_2")
        self.gridlayout.addWidget(self.textLabel3_2, 5, 0, 1, 1)
        self.TextLabel12 = QtGui.QLabel(uClientEditNew)
        self.TextLabel12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel12.setWordWrap(False)
        self.TextLabel12.setObjectName("TextLabel12")
        self.gridlayout.addWidget(self.TextLabel12, 3, 0, 1, 1)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.year = QtGui.QSpinBox(uClientEditNew)
        self.year.setMinimum(2000)
        self.year.setMaximum(2010)
        self.year.setProperty("value", 2003)
        self.year.setObjectName("year")
        self.hboxlayout5.addWidget(self.year)
        spacerItem6 = QtGui.QSpacerItem(66, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem6)
        self.TextLabel4 = QtGui.QLabel(uClientEditNew)
        self.TextLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel4.setWordWrap(False)
        self.TextLabel4.setObjectName("TextLabel4")
        self.hboxlayout5.addWidget(self.TextLabel4)
        self.firstEntry = QtGui.QLineEdit(uClientEditNew)
        self.firstEntry.setObjectName("firstEntry")
        self.hboxlayout5.addWidget(self.firstEntry)
        self.gridlayout.addLayout(self.hboxlayout5, 2, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.textLabel3 = QtGui.QLabel(uClientEditNew)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.vboxlayout.addWidget(self.textLabel3)
        self.TextLabel2.setBuddy(self.year)
        self.TextLabel14.setBuddy(self.accPlan)
        self.textLabel1.setBuddy(uClientEditNew.dimensions)
        self.TextLabel5.setBuddy(uClientEditNew.regNumber)
        self.TextLabel1.setBuddy(self.clients)
        self.TextLabel12.setBuddy(uClientEditNew.periods)
        self.TextLabel4.setBuddy(self.firstEntry)

        self.retranslateUi(uClientEditNew)
        QtCore.QObject.connect(self.pbSave, QtCore.SIGNAL("clicked()"), uClientEditNew.slotSave)
        QtCore.QObject.connect(self.pbCancel, QtCore.SIGNAL("clicked()"), uClientEditNew.slotCancel)
        QtCore.QObject.connect(self.clients, QtCore.SIGNAL("activated(QString)"), uClientEditNew.slotClientSelected)
        QtCore.QMetaObject.connectSlotsByName(uClientEditNew)
        uClientEditNew.setTabOrder(self.clients, self.regNum)
        uClientEditNew.setTabOrder(self.regNum, self.firstEntry)
        uClientEditNew.setTabOrder(self.firstEntry, self.periodes)
        uClientEditNew.setTabOrder(self.periodes, self.accPlan)
        uClientEditNew.setTabOrder(self.accPlan, self.budget)
        uClientEditNew.setTabOrder(self.budget, self.dimension)
        uClientEditNew.setTabOrder(self.dimension, self.vat)
        uClientEditNew.setTabOrder(self.vat, self.pbSave)
        uClientEditNew.setTabOrder(self.pbSave, self.pbCancel)

    def retranslateUi(self, uClientEditNew):
        uClientEditNew.setWindowTitle(QtGui.QApplication.translate("uClientEditNew", "Edit client", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel2.setText(QtGui.QApplication.translate("uClientEditNew", "Year", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("uClientEditNew", "VAT file", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel14.setText(QtGui.QApplication.translate("uClientEditNew", "Account plan", None, QtGui.QApplication.UnicodeUTF8))
        self.vat.setText(QtGui.QApplication.translate("uClientEditNew", "VAT", None, QtGui.QApplication.UnicodeUTF8))
        self.budget.setText(QtGui.QApplication.translate("uClientEditNew", "Budget", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("uClientEditNew", "Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel5.setText(QtGui.QApplication.translate("uClientEditNew", "Reg number", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel1.setText(QtGui.QApplication.translate("uClientEditNew", "Client name", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSave.setText(QtGui.QApplication.translate("uClientEditNew", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("uClientEditNew", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel12.setText(QtGui.QApplication.translate("uClientEditNew", "Periods a year", None, QtGui.QApplication.UnicodeUTF8))
        self.TextLabel4.setText(QtGui.QApplication.translate("uClientEditNew", "First journal entry", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    uClientEditNew = QtGui.QDialog()
    ui = Ui_uClientEditNew()
    ui.setupUi(uClientEditNew)
    uClientEditNew.show()
    sys.exit(app.exec_())

