# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uCuven.ui'
#
# Created: Sat Jan  2 00:55:03 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_uCuven(object):
    def setupUi(self, uCuven):
        uCuven.setObjectName("uCuven")
        uCuven.resize(429, 213)
        font = QtGui.QFont()
        font.setFamily("Adobe Helvetica")
        font.setPointSize(12)
        uCuven.setFont(font)
        self.vboxlayout = QtGui.QVBoxLayout(uCuven)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.wGroup = QtGui.QComboBox(uCuven)
        self.wGroup.setEnabled(False)
        self.wGroup.setMinimumSize(QtCore.QSize(300, 0))
        self.wGroup.setObjectName("wGroup")
        self.gridlayout.addWidget(self.wGroup, 3, 1, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.wNumber = QtGui.QLineEdit(uCuven)
        self.wNumber.setEnabled(False)
        self.wNumber.setMinimumSize(QtCore.QSize(100, 0))
        self.wNumber.setObjectName("wNumber")
        self.hboxlayout.addWidget(self.wNumber)
        spacerItem = QtGui.QSpacerItem(151, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.gridlayout.addLayout(self.hboxlayout, 0, 1, 1, 1)
        self.wRegno = QtGui.QLineEdit(uCuven)
        self.wRegno.setMinimumSize(QtCore.QSize(100, 0))
        self.wRegno.setObjectName("wRegno")
        self.gridlayout.addWidget(self.wRegno, 2, 1, 1, 1)
        self.textLabel3 = QtGui.QLabel(uCuven)
        self.textLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.gridlayout.addWidget(self.textLabel3, 1, 0, 1, 1)
        self.wName = QtGui.QLineEdit(uCuven)
        self.wName.setMinimumSize(QtCore.QSize(300, 0))
        self.wName.setObjectName("wName")
        self.gridlayout.addWidget(self.wName, 1, 1, 1, 1)
        self.textLabel4 = QtGui.QLabel(uCuven)
        self.textLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridlayout.addWidget(self.textLabel4, 0, 0, 1, 1)
        self.textLabel5 = QtGui.QLabel(uCuven)
        self.textLabel5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.gridlayout.addWidget(self.textLabel5, 2, 0, 1, 1)
        self.textLabel3_2 = QtGui.QLabel(uCuven)
        self.textLabel3_2.setEnabled(False)
        self.textLabel3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName("textLabel3_2")
        self.gridlayout.addWidget(self.textLabel3_2, 3, 0, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        spacerItem1 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem2 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem2)
        self.wSave = QtGui.QPushButton(uCuven)
        self.wSave.setAutoDefault(False)
        self.wSave.setObjectName("wSave")
        self.hboxlayout1.addWidget(self.wSave)
        self.wCancel = QtGui.QPushButton(uCuven)
        self.wCancel.setAutoDefault(False)
        self.wCancel.setObjectName("wCancel")
        self.hboxlayout1.addWidget(self.wCancel)
        self.vboxlayout.addLayout(self.hboxlayout1)

        self.retranslateUi(uCuven)
        QtCore.QObject.connect(self.wSave, QtCore.SIGNAL("clicked()"), uCuven.slotSave)
        QtCore.QObject.connect(self.wCancel, QtCore.SIGNAL("clicked()"), uCuven.slotCancel)
        QtCore.QMetaObject.connectSlotsByName(uCuven)
        uCuven.setTabOrder(self.wName, self.wRegno)
        uCuven.setTabOrder(self.wRegno, self.wSave)
        uCuven.setTabOrder(self.wSave, self.wCancel)
        uCuven.setTabOrder(self.wCancel, self.wGroup)
        uCuven.setTabOrder(self.wGroup, self.wNumber)

    def retranslateUi(self, uCuven):
        uCuven.setWindowTitle(QtGui.QApplication.translate("uCuven", "Customers and vendors", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("uCuven", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("uCuven", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5.setText(QtGui.QApplication.translate("uCuven", "Reg number", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3_2.setText(QtGui.QApplication.translate("uCuven", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.wSave.setText(QtGui.QApplication.translate("uCuven", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.wCancel.setText(QtGui.QApplication.translate("uCuven", "Cancel", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    uCuven = QtGui.QDialog()
    ui = Ui_uCuven()
    ui.setupUi(uCuven)
    uCuven.show()
    sys.exit(app.exec_())

