# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uRule.ui'
#
# Created: Sat Jan  2 00:55:11 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_uRule(object):
    def setupUi(self, uRule):
        uRule.setObjectName("uRule")
        uRule.resize(432, 518)
        font = QtGui.QFont()
        font.setFamily("Adobe Helvetica")
        font.setPointSize(12)
        uRule.setFont(font)
        self.vboxlayout = QtGui.QVBoxLayout(uRule)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.wText = QtGui.QLineEdit(uRule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wText.sizePolicy().hasHeightForWidth())
        self.wText.setSizePolicy(sizePolicy)
        self.wText.setObjectName("wText")
        self.gridlayout.addWidget(self.wText, 1, 1, 1, 1)
        self.textLabel5 = QtGui.QLabel(uRule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel5.sizePolicy().hasHeightForWidth())
        self.textLabel5.setSizePolicy(sizePolicy)
        self.textLabel5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.gridlayout.addWidget(self.textLabel5, 4, 0, 1, 1)
        self.textLabel3 = QtGui.QLabel(uRule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel3.sizePolicy().hasHeightForWidth())
        self.textLabel3.setSizePolicy(sizePolicy)
        self.textLabel3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.gridlayout.addWidget(self.textLabel3, 2, 0, 1, 1)
        self.textLabel2 = QtGui.QLabel(uRule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel2.sizePolicy().hasHeightForWidth())
        self.textLabel2.setSizePolicy(sizePolicy)
        self.textLabel2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.gridlayout.addWidget(self.textLabel2, 1, 0, 1, 1)
        self.textLabel4 = QtGui.QLabel(uRule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel4.sizePolicy().hasHeightForWidth())
        self.textLabel4.setSizePolicy(sizePolicy)
        self.textLabel4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridlayout.addWidget(self.textLabel4, 3, 0, 1, 1)
        self.textLabel1 = QtGui.QLabel(uRule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel1.sizePolicy().hasHeightForWidth())
        self.textLabel1.setSizePolicy(sizePolicy)
        self.textLabel1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 0, 0, 1, 1)
        self.wName = QtGui.QLineEdit(uRule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wName.sizePolicy().hasHeightForWidth())
        self.wName.setSizePolicy(sizePolicy)
        self.wName.setObjectName("wName")
        self.gridlayout.addWidget(self.wName, 0, 1, 1, 1)
        self.wPars = QtGui.QTableWidget(uRule)
        self.wPars.setObjectName("wPars")
        self.wPars.setColumnCount(0)
        self.wPars.setRowCount(0)
        self.gridlayout.addWidget(self.wPars, 2, 1, 1, 1)
        self.wPrelude = QtGui.QPlainTextEdit(uRule)
        self.wPrelude.setObjectName("wPrelude")
        self.gridlayout.addWidget(self.wPrelude, 3, 1, 1, 1)
        self.wTabPost = QtGui.QTableWidget(uRule)
        self.wTabPost.setObjectName("wTabPost")
        self.wTabPost.setColumnCount(0)
        self.wTabPost.setRowCount(0)
        self.gridlayout.addWidget(self.wTabPost, 4, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        spacerItem = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem1 = QtGui.QSpacerItem(81, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.wOK = QtGui.QPushButton(uRule)
        self.wOK.setObjectName("wOK")
        self.hboxlayout.addWidget(self.wOK)
        self.wNew = QtGui.QPushButton(uRule)
        self.wNew.setObjectName("wNew")
        self.hboxlayout.addWidget(self.wNew)
        self.wExit = QtGui.QPushButton(uRule)
        self.wExit.setObjectName("wExit")
        self.hboxlayout.addWidget(self.wExit)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(uRule)
        QtCore.QMetaObject.connectSlotsByName(uRule)

    def retranslateUi(self, uRule):
        self.textLabel5.setText(QtGui.QApplication.translate("uRule", "Postings", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("uRule", "Parametres", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("uRule", "Default text", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("uRule", "Prelude", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("uRule", "Rule name", None, QtGui.QApplication.UnicodeUTF8))
        self.wOK.setText(QtGui.QApplication.translate("uRule", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.wNew.setText(QtGui.QApplication.translate("uRule", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.wExit.setText(QtGui.QApplication.translate("uRule", "Exit", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    uRule = QtGui.QDialog()
    ui = Ui_uRule()
    ui.setupUi(uRule)
    uRule.show()
    sys.exit(app.exec_())

