# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uSourceSelect.ui'
#
# Created: Sat Jan  2 00:55:05 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_uSourceSelect(object):
    def setupUi(self, uSourceSelect):
        uSourceSelect.setObjectName("uSourceSelect")
        uSourceSelect.resize(350, 295)
        font = QtGui.QFont()
        font.setFamily("Adobe Helvetica")
        font.setPointSize(12)
        uSourceSelect.setFont(font)
        self.vboxlayout = QtGui.QVBoxLayout(uSourceSelect)
        self.vboxlayout.setObjectName("vboxlayout")
        self.wGroup = QtGui.QGroupBox(uSourceSelect)
        self.wGroup.setObjectName("wGroup")
        self.gridlayout = QtGui.QGridLayout(self.wGroup)
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 4, 2, 1, 1)
        self.wSourceFrom = QtGui.QLineEdit(self.wGroup)
        self.wSourceFrom.setObjectName("wSourceFrom")
        self.gridlayout.addWidget(self.wSourceFrom, 1, 1, 1, 1)
        self.wAccountTo = QtGui.QLineEdit(self.wGroup)
        self.wAccountTo.setObjectName("wAccountTo")
        self.gridlayout.addWidget(self.wAccountTo, 3, 2, 1, 1)
        self.wSourceTo = QtGui.QLineEdit(self.wGroup)
        self.wSourceTo.setObjectName("wSourceTo")
        self.gridlayout.addWidget(self.wSourceTo, 1, 2, 1, 1)
        self.wbSource = QtGui.QRadioButton(self.wGroup)
        self.wbSource.setObjectName("wbSource")
        self.gridlayout.addWidget(self.wbSource, 1, 0, 1, 1)
        self.wAccountFrom = QtGui.QLineEdit(self.wGroup)
        self.wAccountFrom.setObjectName("wAccountFrom")
        self.gridlayout.addWidget(self.wAccountFrom, 3, 1, 1, 1)
        self.wbDate = QtGui.QRadioButton(self.wGroup)
        self.wbDate.setObjectName("wbDate")
        self.gridlayout.addWidget(self.wbDate, 2, 0, 1, 1)
        self.wbAccount = QtGui.QRadioButton(self.wGroup)
        self.wbAccount.setObjectName("wbAccount")
        self.gridlayout.addWidget(self.wbAccount, 3, 0, 1, 1)
        self.wbPeriod = QtGui.QRadioButton(self.wGroup)
        self.wbPeriod.setObjectName("wbPeriod")
        self.gridlayout.addWidget(self.wbPeriod, 4, 0, 1, 1)
        self.wPeriod = QtGui.QComboBox(self.wGroup)
        self.wPeriod.setObjectName("wPeriod")
        self.gridlayout.addWidget(self.wPeriod, 4, 1, 1, 1)
        self.textLabel1 = QtGui.QLabel(self.wGroup)
        self.textLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 0, 1, 1, 1)
        self.textLabel1_2 = QtGui.QLabel(self.wGroup)
        self.textLabel1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridlayout.addWidget(self.textLabel1_2, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(41, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.wbAll = QtGui.QRadioButton(self.wGroup)
        self.wbAll.setObjectName("wbAll")
        self.gridlayout.addWidget(self.wbAll, 5, 0, 1, 1)
        self.wDateFrom = QtGui.QDateEdit(self.wGroup)
        self.wDateFrom.setObjectName("wDateFrom")
        self.gridlayout.addWidget(self.wDateFrom, 2, 1, 1, 1)
        self.wDateTo = QtGui.QDateEdit(self.wGroup)
        self.wDateTo.setObjectName("wDateTo")
        self.gridlayout.addWidget(self.wDateTo, 2, 2, 1, 1)
        self.vboxlayout.addWidget(self.wGroup)
        self.wShowSplits = QtGui.QCheckBox(uSourceSelect)
        self.wShowSplits.setChecked(True)
        self.wShowSplits.setObjectName("wShowSplits")
        self.vboxlayout.addWidget(self.wShowSplits)
        spacerItem2 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem3 = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem3)
        self.wOK = QtGui.QPushButton(uSourceSelect)
        self.wOK.setAutoDefault(False)
        self.wOK.setObjectName("wOK")
        self.hboxlayout.addWidget(self.wOK)
        self.wCancel = QtGui.QPushButton(uSourceSelect)
        self.wCancel.setAutoDefault(False)
        self.wCancel.setObjectName("wCancel")
        self.hboxlayout.addWidget(self.wCancel)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(uSourceSelect)
        QtCore.QMetaObject.connectSlotsByName(uSourceSelect)
        uSourceSelect.setTabOrder(self.wSourceFrom, self.wSourceTo)
        uSourceSelect.setTabOrder(self.wSourceTo, self.wAccountFrom)
        uSourceSelect.setTabOrder(self.wAccountFrom, self.wAccountTo)
        uSourceSelect.setTabOrder(self.wAccountTo, self.wOK)
        uSourceSelect.setTabOrder(self.wOK, self.wCancel)

    def retranslateUi(self, uSourceSelect):
        uSourceSelect.setWindowTitle(QtGui.QApplication.translate("uSourceSelect", "Select source", None, QtGui.QApplication.UnicodeUTF8))
        self.wGroup.setTitle(QtGui.QApplication.translate("uSourceSelect", "Selection criterium", None, QtGui.QApplication.UnicodeUTF8))
        self.wbSource.setText(QtGui.QApplication.translate("uSourceSelect", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.wbDate.setText(QtGui.QApplication.translate("uSourceSelect", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.wbAccount.setText(QtGui.QApplication.translate("uSourceSelect", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.wbPeriod.setText(QtGui.QApplication.translate("uSourceSelect", "Period", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("uSourceSelect", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("uSourceSelect", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.wbAll.setText(QtGui.QApplication.translate("uSourceSelect", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.wShowSplits.setText(QtGui.QApplication.translate("uSourceSelect", "Show splits", None, QtGui.QApplication.UnicodeUTF8))
        self.wOK.setText(QtGui.QApplication.translate("uSourceSelect", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.wCancel.setText(QtGui.QApplication.translate("uSourceSelect", "Cancel", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    uSourceSelect = QtGui.QDialog()
    ui = Ui_uSourceSelect()
    ui.setupUi(uSourceSelect)
    uSourceSelect.show()
    sys.exit(app.exec_())

