# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uSource.ui'
#
# Created: Sat Jan  2 00:54:55 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_uSource(object):
    def setupUi(self, uSource):
        uSource.setObjectName("uSource")
        uSource.resize(596, 509)
        font = QtGui.QFont()
        font.setFamily("Adobe Helvetica")
        font.setPointSize(12)
        uSource.setFont(font)
        self.vboxlayout = QtGui.QVBoxLayout(uSource)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.textLabel1 = QtGui.QLabel(uSource)
        self.textLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 4, 0, 1, 1)
        self.textLabel3 = QtGui.QLabel(uSource)
        self.textLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.gridlayout.addWidget(self.textLabel3, 0, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.wDate = QtGui.QDateEdit(uSource)
        self.wDate.setObjectName("wDate")
        self.hboxlayout.addWidget(self.wDate)
        spacerItem = QtGui.QSpacerItem(180, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.textLabel2 = QtGui.QLabel(uSource)
        self.textLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.hboxlayout.addWidget(self.textLabel2)
        self.wNum = QtGui.QLabel(uSource)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wNum.sizePolicy().hasHeightForWidth())
        self.wNum.setSizePolicy(sizePolicy)
        self.wNum.setMinimumSize(QtCore.QSize(100, 0))
        self.wNum.setFrameShape(QtGui.QFrame.StyledPanel)
        self.wNum.setFrameShadow(QtGui.QFrame.Sunken)
        self.wNum.setWordWrap(False)
        self.wNum.setObjectName("wNum")
        self.hboxlayout.addWidget(self.wNum)
        self.gridlayout.addLayout(self.hboxlayout, 0, 1, 1, 1)
        self.wCuvenLabel = QtGui.QLabel(uSource)
        self.wCuvenLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wCuvenLabel.setWordWrap(False)
        self.wCuvenLabel.setObjectName("wCuvenLabel")
        self.gridlayout.addWidget(self.wCuvenLabel, 1, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.wRule = QtGui.QComboBox(uSource)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(232)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wRule.sizePolicy().hasHeightForWidth())
        self.wRule.setSizePolicy(sizePolicy)
        self.wRule.setMinimumSize(QtCore.QSize(270, 0))
        self.wRule.setObjectName("wRule")
        self.hboxlayout1.addWidget(self.wRule)
        self.gridlayout.addLayout(self.hboxlayout1, 3, 1, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.wLotTable = QtGui.QTableWidget(uSource)
        self.wLotTable.setObjectName("wLotTable")
        self.wLotTable.setColumnCount(0)
        self.wLotTable.setRowCount(0)
        self.hboxlayout2.addWidget(self.wLotTable)
        self.gridlayout.addLayout(self.hboxlayout2, 4, 1, 1, 1)
        self.textLabel17 = QtGui.QLabel(uSource)
        self.textLabel17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel17.setWordWrap(False)
        self.textLabel17.setObjectName("textLabel17")
        self.gridlayout.addWidget(self.textLabel17, 3, 0, 1, 1)
        self.textLabel4 = QtGui.QLabel(uSource)
        self.textLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridlayout.addWidget(self.textLabel4, 2, 0, 1, 1)
        self.wCuven = QtGui.QLineEdit(uSource)
        self.wCuven.setObjectName("wCuven")
        self.gridlayout.addWidget(self.wCuven, 1, 1, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.wCaption = QtGui.QLineEdit(uSource)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wCaption.sizePolicy().hasHeightForWidth())
        self.wCaption.setSizePolicy(sizePolicy)
        self.wCaption.setObjectName("wCaption")
        self.hboxlayout3.addWidget(self.wCaption)
        self.wAutoCapt = QtGui.QCheckBox(uSource)
        self.wAutoCapt.setEnabled(False)
        self.wAutoCapt.setObjectName("wAutoCapt")
        self.hboxlayout3.addWidget(self.wAutoCapt)
        self.gridlayout.addLayout(self.hboxlayout3, 2, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        spacerItem1 = QtGui.QSpacerItem(220, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem1)
        self.wVatCombo = QtGui.QComboBox(uSource)
        self.wVatCombo.setDuplicatesEnabled(False)
        self.wVatCombo.setObjectName("wVatCombo")
        self.hboxlayout4.addWidget(self.wVatCombo)
        self.vboxlayout.addLayout(self.hboxlayout4)
        self.wTable = SplitTable(uSource)
        self.wTable.setMinimumSize(QtCore.QSize(100, 150))
        self.wTable.setObjectName("wTable")
        self.vboxlayout.addWidget(self.wTable)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.wClear = QtGui.QPushButton(uSource)
        self.wClear.setAutoDefault(False)
        self.wClear.setObjectName("wClear")
        self.hboxlayout5.addWidget(self.wClear)
        spacerItem2 = QtGui.QSpacerItem(100, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem2)
        self.wResc = QtGui.QPushButton(uSource)
        self.wResc.setAutoDefault(False)
        self.wResc.setObjectName("wResc")
        self.hboxlayout5.addWidget(self.wResc)
        self.wRound = QtGui.QPushButton(uSource)
        self.wRound.setAutoDefault(False)
        self.wRound.setObjectName("wRound")
        self.hboxlayout5.addWidget(self.wRound)
        self.wBalance = QtGui.QLabel(uSource)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wBalance.sizePolicy().hasHeightForWidth())
        self.wBalance.setSizePolicy(sizePolicy)
        self.wBalance.setMinimumSize(QtCore.QSize(200, 0))
        self.wBalance.setMaximumSize(QtCore.QSize(200, 32767))
        self.wBalance.setFrameShape(QtGui.QFrame.StyledPanel)
        self.wBalance.setFrameShadow(QtGui.QFrame.Sunken)
        self.wBalance.setWordWrap(False)
        self.wBalance.setObjectName("wBalance")
        self.hboxlayout5.addWidget(self.wBalance)
        self.vboxlayout.addLayout(self.hboxlayout5)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem3)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.wPrev = QtGui.QPushButton(uSource)
        self.wPrev.setAutoDefault(False)
        self.wPrev.setObjectName("wPrev")
        self.hboxlayout6.addWidget(self.wPrev)
        self.wNext = QtGui.QPushButton(uSource)
        self.wNext.setAutoDefault(False)
        self.wNext.setObjectName("wNext")
        self.hboxlayout6.addWidget(self.wNext)
        spacerItem4 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem4)
        self.wSave = QtGui.QPushButton(uSource)
        self.wSave.setAutoDefault(False)
        self.wSave.setObjectName("wSave")
        self.hboxlayout6.addWidget(self.wSave)
        spacerItem5 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem5)
        self.wExit = QtGui.QPushButton(uSource)
        self.wExit.setAutoDefault(False)
        self.wExit.setObjectName("wExit")
        self.hboxlayout6.addWidget(self.wExit)
        self.wCancel = QtGui.QPushButton(uSource)
        self.wCancel.setAutoDefault(False)
        self.wCancel.setObjectName("wCancel")
        self.hboxlayout6.addWidget(self.wCancel)
        self.vboxlayout.addLayout(self.hboxlayout6)

        self.retranslateUi(uSource)
        QtCore.QMetaObject.connectSlotsByName(uSource)
        uSource.setTabOrder(self.wCuven, self.wCaption)
        uSource.setTabOrder(self.wCaption, self.wRule)
        uSource.setTabOrder(self.wRule, self.wRound)
        uSource.setTabOrder(self.wRound, self.wSave)
        uSource.setTabOrder(self.wSave, self.wAutoCapt)
        uSource.setTabOrder(self.wAutoCapt, self.wVatCombo)
        uSource.setTabOrder(self.wVatCombo, self.wClear)
        uSource.setTabOrder(self.wClear, self.wResc)
        uSource.setTabOrder(self.wResc, self.wPrev)
        uSource.setTabOrder(self.wPrev, self.wNext)
        uSource.setTabOrder(self.wNext, self.wExit)
        uSource.setTabOrder(self.wExit, self.wCancel)

    def retranslateUi(self, uSource):
        uSource.setWindowTitle(QtGui.QApplication.translate("uSource", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("uSource", "Lot", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("uSource", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("uSource", "Ref number", None, QtGui.QApplication.UnicodeUTF8))
        self.wCuvenLabel.setText(QtGui.QApplication.translate("uSource", "Customer/Vendor", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel17.setText(QtGui.QApplication.translate("uSource", "Rule", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("uSource", "Caption", None, QtGui.QApplication.UnicodeUTF8))
        self.wAutoCapt.setText(QtGui.QApplication.translate("uSource", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.wClear.setText(QtGui.QApplication.translate("uSource", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.wResc.setText(QtGui.QApplication.translate("uSource", "Rescontro", None, QtGui.QApplication.UnicodeUTF8))
        self.wRound.setText(QtGui.QApplication.translate("uSource", "Round", None, QtGui.QApplication.UnicodeUTF8))
        self.wPrev.setText(QtGui.QApplication.translate("uSource", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.wNext.setText(QtGui.QApplication.translate("uSource", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.wSave.setText(QtGui.QApplication.translate("uSource", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.wExit.setText(QtGui.QApplication.translate("uSource", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.wCancel.setText(QtGui.QApplication.translate("uSource", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

from Control.SplitTable.ui import SplitTable

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    uSource = QtGui.QDialog()
    ui = Ui_uSource()
    ui.setupUi(uSource)
    uSource.show()
    sys.exit(app.exec_())

