# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uSourceFind.ui'
#
# Created: Sat Jan  2 00:55:01 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_uSourceFind(object):
    def setupUi(self, uSourceFind):
        uSourceFind.setObjectName("uSourceFind")
        uSourceFind.resize(356, 210)
        font = QtGui.QFont()
        font.setFamily("Adobe Helvetica")
        font.setPointSize(12)
        uSourceFind.setFont(font)
        self.vboxlayout = QtGui.QVBoxLayout(uSourceFind)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.wAccountFrom = QtGui.QLineEdit(uSourceFind)
        self.wAccountFrom.setObjectName("wAccountFrom")
        self.gridlayout.addWidget(self.wAccountFrom, 4, 1, 1, 1)
        self.textLabel1_2 = QtGui.QLabel(uSourceFind)
        self.textLabel1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridlayout.addWidget(self.textLabel1_2, 0, 2, 1, 1)
        self.textLabel2 = QtGui.QLabel(uSourceFind)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.gridlayout.addWidget(self.textLabel2, 0, 0, 1, 1)
        self.wFindAmount = QtGui.QCheckBox(uSourceFind)
        self.wFindAmount.setObjectName("wFindAmount")
        self.gridlayout.addWidget(self.wFindAmount, 3, 0, 1, 1)
        self.wNumTo = QtGui.QLineEdit(uSourceFind)
        self.wNumTo.setObjectName("wNumTo")
        self.gridlayout.addWidget(self.wNumTo, 1, 2, 1, 1)
        self.textLabel1 = QtGui.QLabel(uSourceFind)
        self.textLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 0, 1, 1, 1)
        self.wAccountTo = QtGui.QLineEdit(uSourceFind)
        self.wAccountTo.setObjectName("wAccountTo")
        self.gridlayout.addWidget(self.wAccountTo, 4, 2, 1, 1)
        self.wAmountFrom = QtGui.QLineEdit(uSourceFind)
        self.wAmountFrom.setObjectName("wAmountFrom")
        self.gridlayout.addWidget(self.wAmountFrom, 3, 1, 1, 1)
        self.wNumFrom = QtGui.QLineEdit(uSourceFind)
        self.wNumFrom.setObjectName("wNumFrom")
        self.gridlayout.addWidget(self.wNumFrom, 1, 1, 1, 1)
        self.wFindDate = QtGui.QCheckBox(uSourceFind)
        self.wFindDate.setObjectName("wFindDate")
        self.gridlayout.addWidget(self.wFindDate, 2, 0, 1, 1)
        self.wFindAccount = QtGui.QCheckBox(uSourceFind)
        self.wFindAccount.setObjectName("wFindAccount")
        self.gridlayout.addWidget(self.wFindAccount, 4, 0, 1, 1)
        self.wAmountTo = QtGui.QLineEdit(uSourceFind)
        self.wAmountTo.setObjectName("wAmountTo")
        self.gridlayout.addWidget(self.wAmountTo, 3, 2, 1, 1)
        self.wFindNumber = QtGui.QCheckBox(uSourceFind)
        self.wFindNumber.setObjectName("wFindNumber")
        self.gridlayout.addWidget(self.wFindNumber, 1, 0, 1, 1)
        self.wDateFrom = QtGui.QDateEdit(uSourceFind)
        self.wDateFrom.setObjectName("wDateFrom")
        self.gridlayout.addWidget(self.wDateFrom, 2, 1, 1, 1)
        self.wDateTo = QtGui.QDateEdit(uSourceFind)
        self.wDateTo.setObjectName("wDateTo")
        self.gridlayout.addWidget(self.wDateTo, 2, 2, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        spacerItem = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem1 = QtGui.QSpacerItem(201, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.wSearch = QtGui.QPushButton(uSourceFind)
        self.wSearch.setAutoDefault(False)
        self.wSearch.setObjectName("wSearch")
        self.hboxlayout.addWidget(self.wSearch)
        self.wCancel = QtGui.QPushButton(uSourceFind)
        self.wCancel.setAutoDefault(False)
        self.wCancel.setObjectName("wCancel")
        self.hboxlayout.addWidget(self.wCancel)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(uSourceFind)
        QtCore.QMetaObject.connectSlotsByName(uSourceFind)
        uSourceFind.setTabOrder(self.wFindNumber, self.wNumFrom)
        uSourceFind.setTabOrder(self.wNumFrom, self.wNumTo)
        uSourceFind.setTabOrder(self.wNumTo, self.wFindDate)
        uSourceFind.setTabOrder(self.wFindDate, self.wFindAmount)
        uSourceFind.setTabOrder(self.wFindAmount, self.wAmountFrom)
        uSourceFind.setTabOrder(self.wAmountFrom, self.wAmountTo)
        uSourceFind.setTabOrder(self.wAmountTo, self.wFindAccount)
        uSourceFind.setTabOrder(self.wFindAccount, self.wAccountFrom)
        uSourceFind.setTabOrder(self.wAccountFrom, self.wAccountTo)
        uSourceFind.setTabOrder(self.wAccountTo, self.wSearch)
        uSourceFind.setTabOrder(self.wSearch, self.wCancel)

    def retranslateUi(self, uSourceFind):
        uSourceFind.setWindowTitle(QtGui.QApplication.translate("uSourceFind", "Find source", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("uSourceFind", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("uSourceFind", "Search criterium", None, QtGui.QApplication.UnicodeUTF8))
        self.wFindAmount.setText(QtGui.QApplication.translate("uSourceFind", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("uSourceFind", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.wFindDate.setText(QtGui.QApplication.translate("uSourceFind", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.wFindAccount.setText(QtGui.QApplication.translate("uSourceFind", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.wFindNumber.setText(QtGui.QApplication.translate("uSourceFind", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.wSearch.setText(QtGui.QApplication.translate("uSourceFind", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.wCancel.setText(QtGui.QApplication.translate("uSourceFind", "Cancel", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    uSourceFind = QtGui.QDialog()
    ui = Ui_uSourceFind()
    ui.setupUi(uSourceFind)
    uSourceFind.show()
    sys.exit(app.exec_())

